// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVLIZr0-IImCcxMeFBXh8sXfY-ZGHHi6I',
    appId: '1:503321481614:web:dbf82afe7bd2d5b0eb94df',
    messagingSenderId: '503321481614',
    projectId: 't-booky-d4f64',
    authDomain: 't-booky-d4f64.firebaseapp.com',
    storageBucket: 't-booky-d4f64.appspot.com',
    measurementId: 'G-85DSSJWHLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZab_SAbGhIqSKvfSp8MOMrVjIRD-8Fw',
    appId: '1:503321481614:android:ea49b5c863b9e1afeb94df',
    messagingSenderId: '503321481614',
    projectId: 't-booky-d4f64',
    storageBucket: 't-booky-d4f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR8-nAQ0GtFM59N2K0KUkt5BDem0dK6XM',
    appId: '1:503321481614:ios:f682092dc0615887eb94df',
    messagingSenderId: '503321481614',
    projectId: 't-booky-d4f64',
    storageBucket: 't-booky-d4f64.appspot.com',
    iosBundleId: 'com.example.tBooky',
  );
}
